class: "li.pitschmann.knx.core.plugin.statistic.FileStatisticPlugin"

name:
  en: "Statistic Plugin"
  de: "Statistik Plugin"

description:
  en: "Writes a summary of KNX packets and events in defined interval to a file"
  de: "Schreibt eine regelmässige Zusammenfassung von KNX Pakete und Ereignisse in eine Datei"

configs:
- path:
    name:
      en: "Path"
      de: "Pfad"
    description:
      en: "Recommended: Absolute Path"
      de: "Empfohlen: Absoluter Pfad"
- format:
    name:
      en: "Format"
      de: "Format"
    description:
      en: "File Format (e.g. JSON)"
      de: "Dateiformat (e.g. JSON)"
- intervalMs:
    name:
      en: "Interval"
      de: "Intervall"
    description:
      en: "Defines the interval in milliseconds how often the summary of KNX events should be written to the file."
      de: "Intervall in Millisekunden wie oft die Zusammenfassung von KNX Ereignisse in eine Datei geschrieben werden soll."
