sudo: false

language: java

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

script:
  - mvn test-compile compile -B -V
after_success:
  - mvn clean test jacoco:report coveralls:report -Dlogback.configurationFile=logback-off.xml