sudo: false

language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

# Consider only branches below for CI
branches:
  only:
    - master

# Compiles, run test and code coverage
script:
  - mvn clean test jacoco:report coveralls:report -Dlogback.configurationFile=logback-off.xml
