sudo: false

language: java

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

script:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -Dlogback.configurationFile=logback-off.xml -B -V
after_success:
  - mvn clean test jacoco:report coveralls:report -Dlogback.configurationFile=logback-off.xml