class: "li.pitschmann.knx.core.plugin.api.ApiPlugin"

name:
  en: "API Plugin"
  de: "API Plugin"

description:
  en: "API to extend the communication with third-party applications."
  de: "API für die Erweiterung der Kommunikation mit fremden Applikationen."

configs:
  - port:
      name:
        en: "Port"
        de: "Port"
      description:
        en: "Port of API (used by Pippo Web Service)"
        de: "Port von API (für Pippo Web Service)"
